h2o.glm.1 <- function(..., alpha = 0.00, solver='L_BFGS') 
  h2o.glm.wrapper(..., alpha = alpha, solver = solver)
h2o.glm.2 <- function(..., alpha = 0.50) 
  h2o.glm.wrapper(..., alpha = alpha)
h2o.glm.3 <- function(..., alpha = 0.99) 
  h2o.glm.wrapper(..., alpha = alpha)

h2o.rf.11 <- function(..., ntrees =250, nbins = 20, seed = 1,sample_rate = 0.1) 
  h2o.randomForest.wrapper(..., ntrees = ntrees, nbins = nbins,sample_rate = sample_rate, seed = seed)
h2o.rf.12 <- function(..., ntrees =250, nbins = 20, seed = 1,sample_rate = 0.632) 
  h2o.randomForest.wrapper(..., ntrees = ntrees, nbins = nbins,sample_rate = sample_rate, seed = seed)
h2o.rf.13 <- function(..., ntrees =250, nbins = 20, seed = 1,sample_rate = 0.9) 
  h2o.randomForest.wrapper(..., ntrees = ntrees, nbins = nbins,sample_rate = sample_rate, seed = seed)
h2o.rf.21 <- function(..., ntrees =250, nbins = 100, seed = 1,sample_rate = 0.1) 
  h2o.randomForest.wrapper(..., ntrees = ntrees, nbins = nbins,sample_rate = sample_rate, seed = seed)
h2o.rf.22 <- function(..., ntrees =250, nbins = 100, seed = 1,sample_rate = 0.632) 
  h2o.randomForest.wrapper(..., ntrees = ntrees, nbins = nbins,sample_rate = sample_rate, seed = seed)
h2o.rf.23 <- function(..., ntrees =250, nbins = 100, seed = 1,sample_rate = 0.9) 
  h2o.randomForest.wrapper(..., ntrees = ntrees, nbins = nbins,sample_rate = sample_rate, seed = seed)
h2o.rf.31 <- function(..., ntrees =250, nbins = 200, seed = 1,sample_rate = 0.1) 
  h2o.randomForest.wrapper(..., ntrees = ntrees, nbins = nbins,sample_rate = sample_rate, seed = seed)
h2o.rf.32 <- function(..., ntrees =250, nbins = 200, seed = 1,sample_rate = 0.632) 
  h2o.randomForest.wrapper(..., ntrees = ntrees, nbins = nbins,sample_rate = sample_rate, seed = seed)
h2o.rf.33 <- function(..., ntrees =250, nbins = 200, seed = 1,sample_rate = 0.9) 
  h2o.randomForest.wrapper(..., ntrees = ntrees, nbins = nbins,sample_rate = sample_rate, seed = seed)

h2o.gbm.11 <- function(..., learn_rate=0.02, ntrees =500, nbins=20, sample_rate=0.6, max_depth=9, seed = 1)
  h2o.gbm.wrapper(...,learn_rate=learn_rate, ntrees = ntrees, nbins = nbins, max_depth = max_depth,sample_rate=sample_rate, seed = seed)
h2o.gbm.12 <- function(..., learn_rate=0.035, ntrees =500, nbins=20, sample_rate=0.6, max_depth =9, seed = 1)
  h2o.gbm.wrapper(...,learn_rate=learn_rate, ntrees = ntrees, nbins = nbins, max_depth = max_depth,sample_rate=sample_rate, seed = seed)
h2o.gbm.21 <- function(..., learn_rate=0.02, ntrees =500, nbins=20, sample_rate=0.6, max_depth =11, seed = 1)
  h2o.gbm.wrapper(...,learn_rate=learn_rate, ntrees = ntrees, nbins = nbins, max_depth = max_depth,sample_rate=sample_rate, seed = seed)
h2o.gbm.22 <- function(..., learn_rate=0.035, ntrees =500, nbins=20, sample_rate=0.6, max_depth =11, seed = 1)
  h2o.gbm.wrapper(...,learn_rate=learn_rate, ntrees = ntrees, nbins = nbins, max_depth = max_depth,sample_rate=sample_rate, seed = seed)

h2o.deeplearning.1 <- function(..., hidden = c(500,500), activation = "Rectifier", epochs = 50, seed = 1)  
  h2o.deeplearning.wrapper(..., hidden = hidden, activation = activation, seed = seed)
h2o.deeplearning.2 <- function(..., hidden = c(200,200,200), activation = "Tanh", epochs = 50, seed = 1)  
  h2o.deeplearning.wrapper(..., hidden = hidden, activation = activation, seed = seed)
h2o.deeplearning.3 <- function(..., hidden = c(500,500), activation = "RectifierWithDropout", epochs = 20, seed = 1)
  h2o.deeplearning.wrapper(..., hidden = hidden, activation = activation, seed = seed)
h2o.deeplearning.4 <- function(..., hidden = c(500,500), activation = "Rectifier", epochs = 50, seed = 1)  
  h2o.deeplearning.wrapper(..., hidden = hidden, activation = activation, seed = seed)
h2o.deeplearning.5 <- function(..., hidden = c(100,100,100), activation = "Rectifier", epochs = 50, seed = 1)  
  h2o.deeplearning.wrapper(..., hidden = hidden, activation = activation, seed = seed)
h2o.deeplearning.6 <- function(..., hidden = c(50,50), activation = "Rectifier", epochs = 50, seed = 1)  
  h2o.deeplearning.wrapper(..., hidden = hidden, activation = activation, seed = seed)
h2o.deeplearning.7 <- function(..., hidden = c(100,100), activation = "Rectifier", epochs = 50, seed = 1)  
  h2o.deeplearning.wrapper(..., hidden = hidden, activation = activation, seed = seed)